# Generated by Django 5.2.13 on 2026-04-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
