# Generated by Django 5.2.13 on 2026-04-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettemplate',
            name='counts_for_score',
            field=models.BooleanField(default=True, help_text="If unchecked, completing tickets from this template awards 0 points and doesn't affect scoring."),
        ),
    ]
