# Generated by Django 5.2.13 on 2026-04-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_tickettemplate_counts_for_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='counts_for_score',
            field=models.BooleanField(default=True, help_text="If unchecked, completing this ticket awards 0 points and doesn't affect scoring."),
        ),
    ]
