# Generated by Django 5.2.13 on 2026-04-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_tag_ticket_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettemplate',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='templates', to='tickets.tag'),
        ),
    ]
