# Generated by Django 5.2.13 on 2026-04-11 13:36

from django.db import migrations, models
from django.db.models import Max
from django.utils import timezone


def backfill_last_completed_for(apps, schema_editor):
    TicketTemplate = apps.get_model("tickets", "TicketTemplate")
    Completion = apps.get_model("tickets", "Completion")
    Ticket = apps.get_model("tickets", "Ticket")

    for template in TicketTemplate.objects.all().iterator():
        if getattr(template, "last_completed_for", None):
            continue

        dt = (
            Completion.objects.filter(ticket__template_id=template.id)
            .aggregate(Max("completed_at"))
            .get("completed_at__max")
        )
        if dt is None:
            dt = (
                Ticket.objects.filter(template_id=template.id, status="DONE")
                .aggregate(Max("completed_at"))
                .get("completed_at__max")
            )

        last_done_date = None
        if dt is not None:
            # dt may be a datetime (from completed_at). Convert to local date.
            last_done_date = timezone.localdate(dt)
        else:
            # Fallback: if older rows didn't record completed_at, use scheduled_for_date.
            last_done_date = (
                Ticket.objects.filter(template_id=template.id, status="DONE")
                .aggregate(Max("scheduled_for_date"))
                .get("scheduled_for_date__max")
            )

        if last_done_date is None:
            continue

        template.last_completed_for = last_done_date
        template.save(update_fields=["last_completed_for"])

class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_tickettemplate_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettemplate',
            name='last_completed_for',
            field=models.DateField(blank=True, help_text='Date when a ticket from this template was last completed. Used to schedule the next occurrence.', null=True),
        ),
        migrations.RunPython(backfill_last_completed_for, migrations.RunPython.noop),
    ]
