# Generated by Django 5.2.13 on 2026-04-11 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_tickettemplate_last_completed_for'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='completion',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tickets.ticket'),
        ),
        migrations.AddConstraint(
            model_name='completion',
            constraint=models.UniqueConstraint(fields=('ticket', 'completed_by'), name='unique_ticket_completed_by'),
        ),
    ]
