# Generated by Django 5.2.13 on 2026-04-13 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_completion_ticket_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetFeedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('pet', models.CharField(choices=[('CAT', 'Cat'), ('DOG', 'Dog')], max_length=3)),
                ('time', models.CharField(choices=[('AM', 'Morning'), ('PM', 'Evening')], max_length=2)),
                ('fed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pet_feed_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-day', 'pet', 'time'],
                'constraints': [models.UniqueConstraint(fields=('day', 'pet', 'time'), name='unique_pet_feed_per_day')],
            },
        ),
    ]
