# Generated by Django 5.2.13 on 2026-04-14 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_shoppingitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('person', models.CharField(choices=[('CHRIS', 'Chris'), ('MICHELLE', 'Michelle')], max_length=10)),
                ('supplement', models.CharField(choices=[('MULTIVITAMIN', 'Multivitamin'), ('VITAMIN_B12', 'Vitamin B12'), ('CREATINE', 'Creatine'), ('PILLE', 'Pille')], max_length=20)),
                ('taken', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplement_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-day', 'person', 'supplement'],
                'constraints': [models.UniqueConstraint(fields=('day', 'person', 'supplement'), name='unique_supplement_per_day')],
            },
        ),
    ]
