# Generated by Django 5.2.13 on 2026-04-20 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _seed_dashboard(apps, schema_editor):
    DashboardWidget = apps.get_model('tickets', 'DashboardWidget')
    DashboardToggleGroup = apps.get_model('tickets', 'DashboardToggleGroup')
    DashboardToggle = apps.get_model('tickets', 'DashboardToggle')
    DashboardToggleStatus = apps.get_model('tickets', 'DashboardToggleStatus')
    SupplementStatus = apps.get_model('tickets', 'SupplementStatus')

    if DashboardWidget.objects.count() == 0:
        DashboardWidget.objects.create(kind='PET_FEED', title='', order=10, enabled=True)
        DashboardWidget.objects.create(kind='TOGGLES', title='', order=20, enabled=True)
        DashboardWidget.objects.create(kind='SHOPPING_PREVIEW', title='', order=30, enabled=False)

    group_chris, _ = DashboardToggleGroup.objects.get_or_create(
        title='Chris',
        defaults={'order': 10, 'enabled': True},
    )
    group_michelle, _ = DashboardToggleGroup.objects.get_or_create(
        title='Michelle',
        defaults={'order': 20, 'enabled': True},
    )

    def ensure_toggle(group, slug: str, label: str, order: int):
        toggle, _ = DashboardToggle.objects.get_or_create(
            group=group,
            slug=slug,
            defaults={'label': label, 'order': order, 'enabled': True},
        )
        return toggle

    t_multivitamin = ensure_toggle(group_chris, 'multivitamin', 'Multivitamin', 10)
    t_b12 = ensure_toggle(group_chris, 'vitamin-b12', 'Vitamin B12', 20)
    t_creatine = ensure_toggle(group_chris, 'creatine', 'Creatine', 30)
    t_pille = ensure_toggle(group_michelle, 'pille', 'Pille', 10)

    mapping = {
        ('CHRIS', 'MULTIVITAMIN'): t_multivitamin,
        ('CHRIS', 'VITAMIN_B12'): t_b12,
        ('CHRIS', 'CREATINE'): t_creatine,
        ('MICHELLE', 'PILLE'): t_pille,
    }

    for ss in SupplementStatus.objects.all().iterator():
        toggle = mapping.get((ss.person, ss.supplement))
        if not toggle:
            continue
        # Keep the boolean and day; timestamps may differ due to auto_now.
        DashboardToggleStatus.objects.update_or_create(
            day=ss.day,
            toggle_id=toggle.id,
            defaults={
                'on': bool(ss.taken),
                'updated_by_id': ss.updated_by_id,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_supplementstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardToggleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=10)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PET_FEED', 'Pet feed switches'), ('TOGGLES', 'Custom switches'), ('SHOPPING_PREVIEW', 'Shopping list preview')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=10)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DashboardToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('label', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=10)),
                ('enabled', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toggles', to='tickets.dashboardtogglegroup')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DashboardToggleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('on', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('toggle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='tickets.dashboardtoggle')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_toggle_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-day', 'toggle_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='dashboardtoggle',
            constraint=models.UniqueConstraint(fields=('group', 'slug'), name='unique_toggle_slug_per_group'),
        ),
        migrations.AddConstraint(
            model_name='dashboardtogglestatus',
            constraint=models.UniqueConstraint(fields=('day', 'toggle'), name='unique_dashboard_toggle_per_day'),
        ),

                migrations.RunPython(_seed_dashboard, migrations.RunPython.noop),
    ]
