# Generated by Django 5.2.13 on 2026-04-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_dashboardtogglegroup_dashboardwidget_dashboardtoggle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardwidget',
            name='tickets_limit',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='tickets_min_age_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='dashboardwidget',
            name='kind',
            field=models.CharField(choices=[('PET_FEED', 'Pet feed switches'), ('TOGGLES', 'Custom switches'), ('SHOPPING_PREVIEW', 'Shopping list preview'), ('TICKETS_STALE', 'Tickets: not done for N days')], max_length=30),
        ),
    ]
