# Generated by Django 5.2.13 on 2026-04-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_dashboardwidget_tickets_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardwidget',
            name='toggles_show_30d_stats',
            field=models.BooleanField(default=False),
        ),
    ]
