# Generated by Django 5.2.13 on 2026-07-06

from django.conf import settings
from django.db import migrations


def seed_graphs_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))

    graphs_group, _ = Group.objects.get_or_create(name="Graphs")
    for username in {"christopher", "Chris", "Christopher"}:
        user = User.objects.filter(username__iexact=username).first()
        if user is not None:
            user.groups.add(graphs_group)


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0015_weightentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(seed_graphs_group, migrations.RunPython.noop),
    ]