# Generated by Django 5.2.15 on 2026-07-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	dependencies = [
		('tickets', '0017_ticket_priority'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name='TicketChecklistItem',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('text', models.CharField(max_length=200)),
				('is_done', models.BooleanField(default=False)),
				('order', models.PositiveSmallIntegerField(default=1)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='tickets.ticket')),
			],
			options={'ordering': ['order', 'id']},
		),
		migrations.AddConstraint(
			model_name='ticketchecklistitem',
			constraint=models.UniqueConstraint(fields=('ticket', 'order'), name='unique_ticket_checklist_order'),
		),
	]
