# Generated by Django 5.2.15 on 2026-08-03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
	dependencies = [
		('tickets', '0019_useravailability'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name='UserAvailabilityEvent',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('day', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_events', to=settings.AUTH_USER_MODEL)),
				('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_event_creations', to=settings.AUTH_USER_MODEL)),
			],
			options={
				'ordering': ['-day', '-created_at', '-id'],
			},
		),
	]