# Generated by Django 5.2.15 on 2026-10-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_useravailabilityevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravailabilityevent',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='counts_for_score',
            field=models.BooleanField(default=False, help_text="If unchecked, completing this ticket awards 0 points and doesn't affect scoring."),
        ),
    ]
